# Generated by Django 2.1.4 on 2020-11-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Statystyka',
                'proxy': True,
                'verbose_name_plural': 'Statystyka',
                'indexes': [],
            },
            bases=('ur.tag',),
        ),
    ]
