# Generated by Django 2.1.4 on 2020-11-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ur', '0013_auto_20201116_1959'),
        ('stats', '0002_auto_20181220_0200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatsSummary',
        ),
        migrations.CreateModel(
            name='StatsSummary',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'verbose_name_plural': 'Statystyka',
                'verbose_name': 'Statystyka',
            },
            bases=('ur.tag',),
        ),
    ]
