# Generated by Django 2.1.4 on 2020-12-13 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adres email')),
                ('username', models.CharField(default='', max_length=40)),
                ('fname', models.CharField(max_length=50, verbose_name='Imię')),
                ('lname', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('contact', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numer telefonu')),
                ('brygadier', models.BooleanField(blank=True, default=False, null=True, verbose_name='Brygadzista')),
                ('companyName', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Nazwa firmy')),
                ('companyIn', models.CharField(blank=True, choices=[('a', 'Podwykonawca'), ('b', 'Własny')], default=None, max_length=40, null=True, verbose_name='Pracownik')),
                ('departy', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Department', verbose_name='Wydział')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Uzytkownika',
                'verbose_name_plural': 'Użytkownicy',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20, verbose_name='Etat')),
                ('shift_work', models.BooleanField(default=False, verbose_name='Dostepny na zmianach')),
                ('people', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=12, verbose_name='Numer telefonu')),
            ],
            options={
                'verbose_name': 'Etat',
                'verbose_name_plural': 'Etaty',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Position', verbose_name='Etat'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
