# Generated by Django 2.1.4 on 2018-12-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adres email')),
                ('fname', models.CharField(max_length=50, verbose_name='Imię')),
                ('lname', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('contact', models.CharField(blank=True, max_length=12, null=True, verbose_name='Numer telefonu')),
                ('brygadier', models.BooleanField(blank=True, default=False, null=True, verbose_name='Brygadzista')),
                ('companyName', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Nazwa firmy')),
                ('companyIn', models.CharField(blank=True, choices=[('a', 'Podwykonawca'), ('b', 'Własny')], default=None, max_length=40, null=True, verbose_name='Pracownik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administartor')),
            ],
            options={
                'verbose_name_plural': 'Użytkownicy',
                'verbose_name': 'Uzytkownika',
            },
        ),
        migrations.CreateModel(
            name='Departy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departy', models.CharField(max_length=20, verbose_name='Wydział')),
                ('people', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=12, verbose_name='Numer telefonu')),
            ],
            options={
                'verbose_name_plural': 'Wydziały',
                'verbose_name': 'Wydział',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20, verbose_name='Etat')),
                ('shift_work', models.BooleanField(default=False, verbose_name='Dostepny na zmianach')),
                ('people', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=12, verbose_name='Numer telefonu')),
            ],
            options={
                'verbose_name_plural': 'Etaty',
                'verbose_name': 'Etat',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='departy',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Departy', verbose_name='Wydział'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Position', verbose_name='Etat'),
        ),
    ]
