# Generated by Django 2.1.4 on 2020-11-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ur', '0016_auto_20201117_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_symbol', models.CharField(max_length=40, verbose_name='Symbol')),
                ('machine_name', models.CharField(max_length=40, verbose_name='Nazwa')),
                ('serial_numb', models.CharField(max_length=30, verbose_name='Numer seryjny')),
                ('evidence_numb', models.CharField(max_length=40, verbose_name='Numer ewidencyjny')),
                ('machine_type', models.CharField(max_length=40, verbose_name='Model')),
                ('prod_year', models.IntegerField(verbose_name='Rok produkcji')),
                ('usage_machine', models.BooleanField(verbose_name='W eksploatacji')),
                ('machine_image', models.ImageField(blank=True, null=True, upload_to='machine_img', verbose_name='Zdjęcie')),
                ('machine_docu', models.FileField(blank=True, null=True, upload_to='machine_documents', verbose_name='Dokumentacja')),
                ('machine_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Department', verbose_name='Wydział')),
            ],
        ),
        migrations.CreateModel(
            name='PlantObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.CharField(max_length=40, verbose_name='Nazwa obiektu')),
                ('evidence_obj', models.CharField(max_length=40, verbose_name='Numer ewidencyjny')),
                ('obj_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Department', verbose_name='Wydział')),
            ],
        ),
        migrations.AddField(
            model_name='machineevidence',
            name='machine_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.PlantObjects', verbose_name='Lokalizacja'),
        ),
    ]
