# Generated by Django 2.1.4 on 2020-12-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dep', models.CharField(max_length=20, verbose_name='Wydział')),
                ('people', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=12, verbose_name='Numer telefonu')),
            ],
            options={
                'verbose_name': 'Wydział',
                'verbose_name_plural': 'Wydziały',
            },
        ),
        migrations.CreateModel(
            name='MachineEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_symbol', models.CharField(max_length=40, verbose_name='Symbol')),
                ('machine_name', models.CharField(max_length=40, verbose_name='Nazwa')),
                ('serial_numb', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numer seryjny')),
                ('evidence_numb', models.CharField(blank=True, max_length=40, null=True, verbose_name='Numer ewidencyjny')),
                ('machine_type', models.CharField(blank=True, max_length=40, null=True, verbose_name='Model')),
                ('prod_year', models.IntegerField(blank=True, null=True, verbose_name='Rok produkcji')),
                ('usage_machine', models.BooleanField(default=True, verbose_name='W eksploatacji')),
                ('machine_image', models.ImageField(blank=True, null=True, upload_to='machine_img', verbose_name='Zdjęcie')),
                ('machine_docu', models.FileField(blank=True, null=True, upload_to='machine_documents', verbose_name='Dokumentacja')),
                ('machine_depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Department', verbose_name='Wydział')),
            ],
            options={
                'verbose_name': 'Urządzenie',
                'verbose_name_plural': 'Urządzenia',
            },
        ),
        migrations.CreateModel(
            name='PlantObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.CharField(max_length=40, verbose_name='Nazwa obiektu')),
                ('evidence_obj', models.CharField(max_length=40, verbose_name='Numer ewidencyjny')),
                ('obj_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Department', verbose_name='Wydział')),
            ],
            options={
                'verbose_name': 'Obiekt',
                'verbose_name_plural': 'Obiekty',
            },
        ),
        migrations.AddField(
            model_name='machineevidence',
            name='machine_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.PlantObjects', verbose_name='Lokalizacja'),
        ),
    ]
