# Generated by Django 2.1.4 on 2020-11-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineevidence',
            options={'verbose_name': 'Urządzenie', 'verbose_name_plural': 'Urządzenia'},
        ),
        migrations.AlterModelOptions(
            name='plantobjects',
            options={'verbose_name': 'Obiekt', 'verbose_name_plural': 'Obiekty'},
        ),
    ]
