# Generated by Django 2.1.4 on 2020-11-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20201117_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineevidence',
            name='usage_machine',
            field=models.BooleanField(default=True, verbose_name='W eksploatacji'),
        ),
    ]
