# Generated by Django 2.1.4 on 2020-12-13 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fix_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fix_cat', models.CharField(max_length=20, verbose_name='Dział')),
            ],
            options={
                'verbose_name': 'Dział',
                'verbose_name_plural': 'Działy',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_prior', models.CharField(max_length=10, verbose_name='Priorytet')),
            ],
            options={
                'verbose_name': 'Priorytet',
                'verbose_name_plural': 'Priorytety',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name=32423)),
                ('add_date', models.DateField(default=datetime.date(2020, 12, 13), verbose_name='Data dodania')),
                ('expiry_date', models.DateField(default=datetime.date(2020, 12, 13), verbose_name='Do kiedy wkonac zlecenie')),
                ('explain', models.TextField(verbose_name='Opis usterki')),
                ('is_done', models.BooleanField(default=False, verbose_name='Czy wykonano?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='urfiles', verbose_name='Zdjęcie')),
                ('fix_date', models.DateField(blank=True, default=datetime.date(2020, 12, 13), verbose_name='Data usunięcia usterki')),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Department', verbose_name='Wydział')),
                ('fix_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Fix_cat', verbose_name='Dział odpowiedzialny')),
                ('machine', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='machines.MachineEvidence', verbose_name='Urządzenie')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Priority', verbose_name='Priorytet')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
                'ordering': ('expiry_date',),
            },
        ),
        migrations.CreateModel(
            name='Work_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work_cat', models.CharField(max_length=30, verbose_name='Kategoria usterki')),
            ],
            options={
                'verbose_name': 'Kategoria usterki',
                'verbose_name_plural': 'Kategorie usterek',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='work_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Work_cat', verbose_name='Kategoria usterki'),
        ),
    ]
