# Generated by Django 2.1.4 on 2018-12-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dep', models.CharField(max_length=20, verbose_name='Wydział')),
            ],
            options={
                'verbose_name_plural': 'Wydziały',
                'verbose_name': 'Wydział',
            },
        ),
        migrations.CreateModel(
            name='Fix_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fix_cat', models.CharField(max_length=20, verbose_name='Dział')),
            ],
            options={
                'verbose_name_plural': 'Działy',
                'verbose_name': 'Dział',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_prior', models.CharField(max_length=10, verbose_name='Priorytet')),
            ],
            options={
                'verbose_name_plural': 'Priorytety',
                'verbose_name': 'Priorytet',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Numer tagu')),
                ('machine', models.CharField(max_length=20, verbose_name='Urządzenie')),
                ('add_date', models.DateField(verbose_name='Data dodania')),
                ('expiry_date', models.DateField(verbose_name='Data wykonania')),
                ('explain', models.TextField(verbose_name='Opis usterki')),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Department', verbose_name='Wydział')),
                ('fix_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Fix_cat', verbose_name='Dział odpowiedzialny')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Priority', verbose_name='Priorytet')),
            ],
            options={
                'ordering': ('expiry_date',),
                'verbose_name_plural': 'Tagi',
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Work_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work_cat', models.CharField(max_length=30, verbose_name='Kategoria usterki')),
            ],
            options={
                'verbose_name_plural': 'Kategorie usterek',
                'verbose_name': 'Kategoria usterki',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='work_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Work_cat', verbose_name='Kategoria usterki'),
        ),
    ]
