# Generated by Django 2.1.4 on 2020-11-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Numer tagu'),
        ),
    ]
