# Generated by Django 2.1.4 on 2020-11-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ur', '0013_auto_20201116_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='number',
            field=models.CharField(default=None, max_length=20, verbose_name='Numer tagu'),
        ),
    ]
