# Generated by Django 2.1.4 on 2020-11-16 21:13

from django.db import migrations, models
import ur.models


class Migration(migrations.Migration):

    dependencies = [
        ('ur', '0014_auto_20201116_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='number',
            field=models.CharField(default=ur.models.foo, max_length=20, verbose_name='Numer tagu'),
        ),
    ]
