# Generated by Django 2.1.4 on 2020-11-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ur', '0003_auto_20201120_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayForTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_material', models.CharField(max_length=20, verbose_name='Materiał')),
                ('amount_material', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('unit', models.CharField(blank=True, choices=[('a', 'godzina'), ('b', 'metr'), ('c', 'sztuk'), ('d', 'kilogram')], default=None, max_length=40, null=True, verbose_name='Jednostka')),
                ('cost_material', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Koszt jednostkowy')),
                ('tag_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Tag', verbose_name='Rozlicz zlecenie')),
            ],
            options={
                'verbose_name': 'Rozlicz',
                'verbose_name_plural': 'Rozlicz',
            },
        ),
    ]
