# Generated by Django 2.1.4 on 2020-12-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=50, verbose_name='Nazwa firmy')),
                ('cmp_address', models.CharField(max_length=50, verbose_name='Adres')),
                ('cmp_address2', models.CharField(max_length=50, verbose_name='Adres cd.')),
                ('cmp_tel', models.CharField(max_length=50, verbose_name='Numer telefonu')),
            ],
        ),
        migrations.CreateModel(
            name='PayForTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_material', models.CharField(max_length=20, verbose_name='Materiał')),
                ('amount_material', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('unit', models.CharField(blank=True, choices=[('a', 'godzina'), ('b', 'metr'), ('c', 'sztuk'), ('d', 'kilogram')], default=None, max_length=40, null=True, verbose_name='Jednostka')),
                ('cost_material', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
            ],
            options={
                'verbose_name': 'Rozliczenie',
                'verbose_name_plural': 'Rozliczenia',
            },
        ),
        migrations.CreateModel(
            name='TagToPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urcost.CompanyList')),
                ('tag_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Tag', verbose_name='Nazwa zlecenia')),
            ],
        ),
        migrations.AddField(
            model_name='payfortag',
            name='tag_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urcost.TagToPay'),
        ),
    ]
