# Generated by Django 2.1.4 on 2020-11-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ur', '0004_auto_20201121_0921'),
        ('urcost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagToPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50, verbose_name='Nazwa firmy')),
                ('comp_local', models.CharField(max_length=50, verbose_name='Adres')),
                ('tag_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Tag', verbose_name='Rozlicz zlecenie')),
            ],
        ),
        migrations.AlterModelOptions(
            name='payfortag',
            options={'verbose_name': 'Rozliczenie', 'verbose_name_plural': 'Rozliczenia'},
        ),
        migrations.RemoveField(
            model_name='payfortag',
            name='tag_name',
        ),
        migrations.AlterField(
            model_name='payfortag',
            name='cost_material',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena'),
        ),
        migrations.AddField(
            model_name='payfortag',
            name='tag_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urcost.TagToPay'),
        ),
    ]
