# Generated by Django 2.1.4 on 2020-11-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urcost', '0002_auto_20201121_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtopay',
            name='tag_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ur.Tag', verbose_name='Nazwa zlecenia'),
        ),
    ]
